// Frontend_React/src/components/Navbar.jsx
export default function Navbar() {
  return (
    <nav className="bg-white shadow-md">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between h-16">
          <div className="flex items-center">
            <span className="text-2xl mr-2">📦</span>
            <span className="font-bold text-xl text-blue-600">GOMAHTECH Stock</span>
          </div>
          <div className="flex items-center space-x-4">
            <div className="h-8 w-8 bg-blue-100 rounded-full flex items-center justify-center text-blue-600 font-bold">
              A
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
}

// Frontend/src/components/Navbar.vue
<template>
  <nav class="bg-white shadow-md">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between h-16">
        
        <div class="flex items-center">
          <span class="text-2xl mr-2">📦</span>
          <span class="font-bold text-xl text-green-600">GOMAHTECH (Vue)</span>
        </div>

        <div class="flex items-center space-x-4">
          <button class="text-gray-500 hover:text-green-600">Tableau de bord</button>
          <div class="h-8 w-8 bg-green-100 rounded-full flex items-center justify-center text-green-600 font-bold">
            A
          </div>
        </div>

      </div>
    </div>
  </nav>
</template>
