// Frontend_React/src/components/ProductForm.jsx
import { useState } from 'react';

export default function ProductForm({ onProductAdded, onCancel }) {
  // On crée des variables pour stocker ce que l'utilisateur tape
  const [nom, setNom] = useState("");
  const [sku, setSku] = useState("");
  const [prix, setPrix] = useState("");
  const [description, setDescription] = useState("");

  const handleSubmit = (e) => {
    e.preventDefault(); // Empêche la page de se recharger

    // 1. On prépare les données à envoyer
    const newProduct = {
      nom: nom,
      sku: sku,
      prix: parseFloat(prix), // On s'assure que c'est un nombre
      description: description,
      seuil_alerte: 5,
      tenant_id: 1 // On force l'entreprise 1 pour l'instant
    };

    // 2. On envoie au Backend via l'API
    fetch("http://127.0.0.1:8000/products/", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(newProduct),
    })
      .then((res) => {
        if (res.ok) {
          // Si ça marche, on prévient App.jsx pour qu'il rafraîchisse la liste
          onProductAdded();
        } else {
          alert("Erreur lors de la création ! Vérifie le SKU (doublon ?)");
        }
      })
      .catch((err) => console.error(err));
  };

  return (
    <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex justify-center items-center">
      <div className="bg-white p-6 rounded-lg shadow-xl w-96">
        <h2 className="text-xl font-bold mb-4">Ajouter un produit</h2>
        
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700">Nom</label>
            <input type="text" required className="mt-1 block w-full border rounded-md p-2" 
              value={nom} onChange={(e) => setNom(e.target.value)} />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">SKU (Réf unique)</label>
            <input type="text" required className="mt-1 block w-full border rounded-md p-2" 
              value={sku} onChange={(e) => setSku(e.target.value)} />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">Prix (€)</label>
            <input type="number" required className="mt-1 block w-full border rounded-md p-2" 
              value={prix} onChange={(e) => setPrix(e.target.value)} />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">Description</label>
            <textarea className="mt-1 block w-full border rounded-md p-2" 
              value={description} onChange={(e) => setDescription(e.target.value)} />
          </div>

          <div className="flex justify-end space-x-2 mt-4">
            <button type="button" onClick={onCancel} className="px-4 py-2 bg-gray-200 rounded hover:bg-gray-300">
              Annuler
            </button>
            <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
              Créer
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

// Frontend/src/components/ProductForm.vue
<script setup>
import { ref } from 'vue'

// On définit les événements que ce composant peut envoyer au parent (App.vue)
const emit = defineEmits(['close', 'refresh'])

// Les variables du formulaire
const nom = ref("")
const sku = ref("")
const prix = ref("")
const description = ref("")

const handleSubmit = () => {
  // 1. Préparation des données
  const newProduct = {
    nom: nom.value,
    sku: sku.value,
    prix: parseFloat(prix.value),
    description: description.value,
    seuil_alerte: 5,
    tenant_id: 1
  }

  // 2. Envoi au Backend
  fetch("http://127.0.0.1:8000/products/", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(newProduct),
  })
  .then(res => {
    if (res.ok) {
      // Si ça marche, on prévient le parent pour qu'il recharge la liste
      emit('refresh')
      emit('close')
    } else {
      alert("Erreur ! Vérifie le SKU (doublon ?)")
    }
  })
  .catch(err => console.error(err))
}
</script>

<template>
  <div class="fixed inset-0 bg-gray-600 bg-opacity-50 flex justify-center items-center z-50">
    <div class="bg-white p-6 rounded-lg shadow-xl w-96">
      <h2 class="text-xl font-bold mb-4">Ajouter un produit (Vue)</h2>
      
      <form @submit.prevent="handleSubmit" class="space-y-4">
        
        <input v-model="nom" type="text" placeholder="Nom" required class="w-full border p-2 rounded" />
        <input v-model="sku" type="text" placeholder="SKU (Réf unique)" required class="w-full border p-2 rounded" />
        <input v-model="prix" type="number" placeholder="Prix (€)" required class="w-full border p-2 rounded" />
        <textarea v-model="description" placeholder="Description" class="w-full border p-2 rounded"></textarea>
        
        <div class="flex justify-end space-x-2 mt-4">
          <button type="button" @click="$emit('close')" class="px-4 py-2 bg-gray-200 rounded hover:bg-gray-300">
            Annuler
          </button>
          <button type="submit" class="px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700">
            Créer
          </button>
        </div>

      </form>
    </div>
  </div>
</template>
